# ==========================================
# CẤU HÌNH GATEWAY
# ==========================================
gateway.host=localhost
gateway.port=5000
dashboard.port=5005

# ==========================================
# CẤU HÌNH DANH SÁCH BACKEND SERVERS
# ==========================================
server.count=3

server.1.name=Server 1
server.1.host=localhost
server.1.port=5001

server.2.name=Server 2
server.2.host=localhost
server.2.port=5002

server.3.name=Server 3
server.3.host=localhost
server.3.port=5003